language: go

go:
  - 1.6
  - 1.7
  - 1.8
  - tip


before_install:
  - go get -v github.com/golang/lint/golint
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - go test ./...
  - $HOME/gopath/bin/goveralls -service=travis-ci