#!/bin/sh

# Uncomment the following two lines if we are in the hook process
#cd ..
#cd ..
DIR=`pwd`
echo ${DIR}

GOFMT_FILES=$(gofmt -l .)
if [ -n "${GOFMT_FILES}" ]; then
  printf >&2 'gofmt failed for the following files:\n%s\n\nplease run "gofmt -w ." on your changes before committing.' "${GOFMT_FILES}"
  echo
  exit 1
fi

GOLINT_ERRORS=$(golint ./... | grep -v "Id should be \| consider calling")
if [ -n "${GOLINT_ERRORS}" ]; then
  printf >&2 'golint failed for the following reasons:\n%s\n\nplease run "golint ./..." on your changes before committing.\n' "${GOLINT_ERRORS}"
  echo
  exit 1
fi

GOVET_ERRORS=$(go tool vet . 2>&1)
if [ -n "${GOVET_ERRORS}" ]; then
  printf >&2 'go vet failed for the following reasons:\n%s\n\nplease run "go tool vet ." on your changes before committing.\n'  "${GOVET_ERRORS}"
  echo
  exit 1
fi

